// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtNjNf-Zj2pgpvvTzTi6iu163bOiDgXWM',
    appId: '1:726191857317:web:d8e3d7daef01a644aef74c',
    messagingSenderId: '726191857317',
    projectId: 'test-f607f',
    authDomain: 'test-f607f.firebaseapp.com',
    storageBucket: 'test-f607f.appspot.com',
    measurementId: 'G-01Z4JMW0ST',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxPlCZYS1GrI_D_NNjUggBim3VN18IY9M',
    appId: '1:726191857317:android:cb976ab61a43bff1aef74c',
    messagingSenderId: '726191857317',
    projectId: 'test-f607f',
    storageBucket: 'test-f607f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoRHDleU5y_XDWXUiUfSSp5XJBaHUqhsE',
    appId: '1:726191857317:ios:7441c4aa0a82a23eaef74c',
    messagingSenderId: '726191857317',
    projectId: 'test-f607f',
    storageBucket: 'test-f607f.appspot.com',
    iosClientId:
        '726191857317-2lnb07jf1vh2nm47b2mkmg9d1gs93p1c.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoRHDleU5y_XDWXUiUfSSp5XJBaHUqhsE',
    appId: '1:726191857317:ios:763fdf0ccf7c19eaaef74c',
    messagingSenderId: '726191857317',
    projectId: 'test-f607f',
    storageBucket: 'test-f607f.appspot.com',
    iosClientId:
        '726191857317-np6k0du947qjoqoio3isp8pj418pr9mc.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
